# Generated by Django 6.1.1 on 2026-09-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('contato_nome', models.CharField(blank=True, max_length=150)),
                ('contato_email', models.EmailField(blank=True, max_length=254)),
                ('contato_telefone', models.CharField(blank=True, max_length=15)),
                ('comissao_padrao', models.DecimalField(decimal_places=2, default=15.0, help_text='Percentual padrão de comissão, usado quando o Plano não define um próprio.', max_digits=5)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Seguradoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguro', models.CharField(choices=[('auto', 'Automóvel'), ('residencial', 'Residencial'), ('vida', 'Vida')], max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('cobertura_descricao', models.TextField(blank=True)),
                ('percentual_comissao', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para usar o percentual padrão da Seguradora.', max_digits=5, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('seguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='cotacoes.seguradora')),
            ],
            options={
                'ordering': ['seguradora__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Apolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotacao_mongo_id', models.CharField(blank=True, help_text='ID do documento da simulação original no MongoDB, para rastreabilidade.', max_length=50)),
                ('numero_apolice', models.CharField(max_length=30, unique=True)),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_franquia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='ativa', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apolices', to='cotacoes.bem')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apolices', to='cotacoes.cliente')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apolices', to='cotacoes.plano')),
                ('seguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apolices', to='cotacoes.seguradora')),
            ],
            options={
                'verbose_name_plural': 'Apólices',
                'ordering': ['-criado_em'],
            },
        ),
    ]
